Allow vault test to pass if VAULT_ADDR set
If the environment variable VAULT_ADDR is set, as is quite likely with
a regular vault user, the TestVaultConfig test will fail with

                Error:          Not equal:
                                expected: "https://127.0.0.1:8200"
                                actual  : "<VAULT_ADDR>"

This fixes that problem.